dependencies:
  - name: postgresql
    repository: https://charts.helm.sh/stable/
    version: 0.8.3
  - name: postgresql
    repository: https://charts.helm.sh/stable/
    version: 0.8.3
    alias: another-postgresql
